name: Codecov

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # install poetry
      - name: Install poetry
        run: pipx install poetry==1.5.0
      # set-up python with cache
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # install requirements (including dev dependencies)
      - name: Install requirements
        run: |
          poetry install --only code_coverage
          python -m pip install coverage==6.5.0

      - name: Run tests and coverage
        run: |
          coverage run -m unittest discover -s tests/ -p "*_test.py" 

      - name: Upload coverage data to Codecov
        run: codecov --token=${{ secrets.CODECOV_TOKEN }}
