name: DeepSource Analysis

on:
  push:
    branches:
      - master

jobs:
  deepsource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install DeepSource CLI
        run: |
          curl -LO "https://deepsource.io/cli"
          chmod +x cli
          sudo mv cli /usr/local/bin/deepsource

      - name: Run DeepSource analysis
        run: deepsource report
        env:
          DEEPSOURCE_TOKEN: ${{ secrets.DEEPSOURCE_SECRET }}

      - name: Update DeepSource badges
        run: |
          export DEEPSOURCE_API_TOKEN="${{ secrets.DEEPSOURCE_SECRET }}"
          export DEEPSOURCE_ORGANIZATION="isaacksdata"
          export DEEPSOURCE_REPO="dictionary-tools"

          # Fetch the number of issues
          NUMBER_OF_ISSUES=$(curl -s -H "Authorization: Token $DEEPSOURCE_API_TOKEN" "https://deepsource.io/api/$DEEPSOURCE_ORGANIZATION/$DEEPSOURCE_REPO/issues/" | jq '.count')

          # Fetch the number of resolved issues
          NUMBER_OF_RESOLVED_ISSUES=$(curl -s -H "Authorization: Token $DEEPSOURCE_API_TOKEN" "https://deepsource.io/api/$DEEPSOURCE_ORGANIZATION/$DEEPSOURCE_REPO/issues/?status=resolved" | jq '.count')

          # Update the badge URLs in the README or any desired file
          sed -i "s|<badge_url_for_number_of_issues>|https://img.shields.io/badge/DeepSource-Issues-$NUMBER_OF_ISSUES-orange|g" README.md
          sed -i "s|<badge_url_for_number_of_resolved_issues>|https://img.shields.io/badge/DeepSource-Resolved%20Issues-$NUMBER_OF_RESOLVED_ISSUES-green|g" README.md

