# based on https://johschmidt42.medium.com/setting-up-python-projects-part-ii-c4bd84b709d1

name: Linting

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master


jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # install poetry
      - name: Install poetry
        run: pipx install poetry==1.5.0
      # set-up python with cache
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # install requirements (including dev dependencies)
      - name: Install requirements
        run: poetry install --only lint
      # run linters
      - name: Run linters
        run: |
          set -o pipefail
          poetry run make lint