# based on https://johschmidt42.medium.com/setting-up-python-projects-part-ii-c4bd84b709d1

name: Unit Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  Unit_Tests:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # install poetry
      - name: Install poetry
        run: pipx install poetry==1.5.0
      # set-up python with cache
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # install requirements (including dev dependencies)
      - name: Install requirements
        run: |
          poetry install --only unit_tests
          python -m pip install .
      # run unit tests
      - name: Run Unit Tests
        run: |
          cd tests
          python -m unittest
      - name: Update badge
        if: always()
        run: |
          if [[ ${{ job.status }} == 'success' ]]; then
            sed -i -E 's/!\[unit tests\]\([^)]*\)/![unit tests](https:\/\/github.com\/isaacksdata\/dictionary-tools\/actions\/workflows\/unit_tests.yml\/badge.svg)/' README.md
          else
            sed -i -E 's/!\[unit tests\]\([^)]*\)/![unit tests](https:\/\/github.com\/isaacksdata\/dictionary-tools\/actions\/workflows\/unit_tests.yml\/badge.svg?event=push)/' README.md
          fi